---
- name: Create network interface
  hosts: hotspots

  tasks:
    - name: add lan interface
      uci: command=set config=network session=lan10 value=interface

    - name: add lan interface force_link
      uci: command=set config=network session=lan10 option=force_link value=1

    - name: add lan interface ifname
      uci: command=set config=network session=lan10 option=ifname value=eth0.10

    - name: add lan interface type
      uci: command=set config=network session=lan10 option=type value=bridge

    - name: add lan interface proto
      uci: command=set config=network session=lan10 option=proto value=static

    - name: add lan interface ip address
      uci: command=set config=network session=lan10 option=ipaddr value=192.168.122.1

    - name: add lan interface netmask ip address
      uci: command=set config=network session=lan10 option=netmask value=255.255.254.0

    - name: commit network
      uci: command=commit config=network
