---
- name: Create VPN interface
  hosts: hotspots

  tasks:
    - name: add vpn interface
      uci: command=set config=network session=vpn value=interface
      notify: commit vpn

    - name: add vpn interface name
      uci: command=set config=network session=vpn option=ifname value=tun0
      notify: commit vpn

    - name: add vpn protocol
      uci: command=set config=network session=vpn option=proto value=none
      notify: commit vpn

  handlers:
    - name: commit vpn
      uci: command=commit config=network
      notify: restart vpn

    - name: restart vpn
      service: name=openvpn state=restart
