---
- name: Create DHCP address pool
  hosts: hotspots
  vars:
    lan: lan1
    leasetime: 30m

  tasks:
    - name: add dhcp address pool
      uci: command=set config=dhcp session={{lan}} value=dhcp
      notify: commit dhcp

    - name: add dhcp listen interface
      uci: command=set config=dhcp session={{lan}} option=interface value={{lan}}
      notify: commit dhcp

    - name: add dhcp start address
      uci: command=set config=dhcp session={{lan}} option=start value=100
      notify: commit dhcp

    - name: add dhcp limit address
      uci: command=set config=dhcp session={{lan}} option=limit value=150
      notify: commit dhcp

    - name: add dhcp leasetime
      uci: command=set config=dhcp session={{lan}} option=leasetime value={{leasetime}}
      notify: commit dhcp

    - name: add dhcp dhcpv6
      uci: command=set config=dhcp session={{lan}} option=dhcpv6 value=server
      notify: commit dhcp

    - name: add dhcp ra
      uci: command=set config=dhcp session={{lan}} option=ra value=server
      notify: commit dhcp

  handlers:
    - name: commit dhcp
      uci: command=commit config=dhcp
      notify: restart dhcp

    - name: restart dhcp
      service: name=dnsmasq state=restart
