---
- name: Create Wi-Fi ssid
  hosts: hotspots
  vars:
    device: radio0
    lan: lan1
    ssid: ssid
    encryption: none

  tasks:
    - name: add wifi iface
      uci: command=add config=wireless session=wifi-iface
      notify: commit wireless

    - name: set wifi iface device
      uci: command=set config=wireless session=@wifi-iface[-1] option=device value={{device}}
      notify: commit wireless

    - name: set wifi iface network
      uci: command=set config=wireless session=@wifi-iface[-1] option=network value={{lan}}
      notify: commit wireless

    - name: set wifi iface mode
      uci: command=set config=wireless session=@wifi-iface[-1] option=mode value=ap
      notify: commit wireless

    - name: set wifi iface ssid
      uci: command=set config=wireless session=@wifi-iface[-1] option=ssid value={{ssid}}
      notify: commit wireless

    - name: set wifi iface encryption
      uci: command=set config=wireless session=@wifi-iface[-1] option=encryption value={{encryption}}
      notify: commit wireless

  handlers:
    - name: commit wireless
      uci: command=commit config=wireless
      notify: restart network

    - name: restart network
      service: name=network state=restart
